% GLABGLOBAL  Declare global variables for G-Lab.

% Cogent2000 global var.
global cogent

% G-Lab global vars
global GLAB_STATUS GLAB_IS_RUNNING GLAB_IS_ABORT GLAB_CURRENT_PRIORITY GLAB_DEBUG
global GLAB_LIBRARIES
global GLAB_DISPLAY GLAB_BUFFERS
global GLAB_KEYBOARD GLAB_SERIALPORT GLAB_PARALLELPORT
global GLAB_PHOTODIODE GLAB_EYELINK GLAB_PSB GLAB_TDT
global GLAB_TRIAL GLAB_FUNCTIONS
