% COSYGLOBAL  Declare global variables for CosyGraphics.

% Cogent2000 global var.
global cogent

% CosyGraphics global vars
global COSY_GENERAL COSY_TRIALLOG COSY_FUNCTIONS
global COSY_DISPLAY COSY_SOUND COSY_VIDEO
global COSY_KEYBOARD COSY_PARALLELPORT COSY_SERIALPORT_DAQ 
global COSY_PHOTODIODE COSY_EYELINK COSY_PSB COSY_TDT
global COSY_SCORE